apiVersion: v1
data:
  username: Z2l0ZWE=
  password: Z2l0ZWE=
kind: Secret
metadata:
  name: gitea-postgres-secret
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-initdb
spec:
  instances: 3
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-postgres-secret
  storage:
    size: 1Gi
