apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-dragonfly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/dragonflydb/dragonfly/helm/dragonfly
    chart: dragonfly
    targetRevision: v1.29.0
  destination:
    server: https://kubernetes.default.svc
    namespace: unimagic-gitea
  syncPolicy:
    syncOptions:
      - ServerSideApply=true

