apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 11.0.1
    helm:
      valueFiles:
        - $repo/unimagic-gitea/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: unimagic-gitea
  syncPolicy:
    syncOptions:
      - ServerSideApply=true

