apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-meilisearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    chart: meilisearch
    targetRevision: 0.12.0
  destination:
    server: https://kubernetes.default.svc
    namespace: unimagic-gitea
  syncPolicy:
    syncOptions:
      - ServerSideApply=true

