apiVersion: v1
kind: ConfigMap
metadata:
  name: image-slide-nginx-config
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      proxy_intercept_errors on;
      gzip on;
      gzip_types text/plain;

      location / {
        proxy_pass http://127.0.0.1:3000;
        real_ip_recursive on;
        real_ip_header    X-Forwarded-For;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /dev/null;
      }
    }
