apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-files-pvc
  namespace: unimagic-redmine
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
