apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unimagic-redmine
  name: redmine
  labels:
    app: redmine
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - image: redmine:6-alpine
          name: redmine
          env:
            - name: REDMINE_DB_MYSQL
              valueFrom:
                secretKeyRef:
                  name: redmine-appsettings
                  key: db_host
            - name: REDMINE_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: redmine-appsettings
                  key: db_name
            - name: REDMINE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redmine-appsettings
                  key: db_username
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-appsettings
                  key: db_password
          volumeMounts:
            - name: redmine-files-persistent-storage
              mountPath: /usr/src/redmine/files
      volumes:
        - name: redmine-files-persistent-storage
          persistentVolumeClaim:
            claimName: redmine-files-pvc
