kind: Service
apiVersion: v1
metadata:
  namespace: unimagic-redmine
  name: unimagic-redmine-svc
spec:
  selector:
    app: redmine
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer