apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-weather
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: geo-weather
  replicas: 2
  template:
    metadata:
      labels:
        app: geo-weather
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - geo-weather
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: geo-weather
          image: ghcr.io/o-tr/geo-weather:sha256-bc0297c52404ba2859177807c64b241ba2a043432af25c390fdcbe8383f69f4f
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 180
            periodSeconds: 10
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: geo-weather-config
          env:
            - name: TZ
              value: Asia/Tokyo
---
kind: Service
apiVersion: v1
metadata:
  name: geo-weather-svc
spec:
  selector:
    app: geo-weather
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: geo-weather-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: geo-weather
